name: Continuous Integration (Test)

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
  pull_request:
    branches:
      - main

concurrency:
  group: ci-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install
      - name: Run
        run: bun run test
