name: Generate Types

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.ts'
      - '**.json'
  pull_request:
    branches:
      - main

concurrency:
  group: generate-types-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate-types:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install
      - name: Run
        run: bun run generate-types
      - name: Push
        continue-on-error: true
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A ./generated
          git commit -m "Update generated types"
          git push
